language: java
sudo: false

jdk:
  - openjdk6

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  - IDEA_VERSION=IC-2016.1.4
  - IDEA_VERSION=IC-2016.1.3
  - IDEA_VERSION=IC-2016.1.2
  - IDEA_VERSION=IC-2016.1

before_install:
 - chmod +x gradlew
 - pip install --user codecov

after_success:
  - codecov

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/33baacd26d1b840aebaa
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
